unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

" Backups
set backup
set writebackup
"" mkdir -p $XDG_STATE_HOME/vim/backups
set backupdir=$XDG_STATE_HOME/vim/backups

set undofile
"" mkdir -p $XDG_STATE_HOME/vim/undofiles
set undodir=$XDG_STATE_HOME/vim/undofiles
set viminfofile=$XDG_STATE_HOME/vim/viminfo




" Enables some in built packages
packadd! comment
packadd! editorconfig
packadd! helptoc
packadd! matchit
packadd! nohlsearch

" Loads man plugin
runtime ftplugin/man.vim

" UI elements
colorscheme unokai
set number
set relativenumber
set cursorline
set wildmode=longest,full

" Set fold
set foldmethod=syntax
set foldlevel=2

" Indentation
set tabstop=8
set shiftwidth=4
set softtabstop=-1
set noexpandtab

" Add tags from $VIMRUNTIME
set tags+=$VIMRUNTIME/doc/tags

" Rust plugin settings
"" Folding
let g:rust_fold = 2
"" Autosaving
let g:rustfmt_autosave = 1
